[projects]
default = "676eb189-4e38-404e-b990-6824676a55d6"

[services.backend]
path = "backend"
build = "npm install && npm run build"
start = "npm start"

[services.client]
path = "client"
build = "npm install && npm run build"
start = "serve -s build"
